--- #YAML:1.0
name:                Acme-Spinner
version:             0.03
abstract:            The great new Acme::Spinner!
license:             ~
author:              
    - Chris Fedde <cfedde at cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
